//
//  AnalysisOutput.swift
//  Insio Health
//
//  Structured analysis output for workout insights.
//  This model represents the structured data produced by local rules/calculations.
//  In the future, OpenAI can be used to rewrite this into user-facing narrative.
//
//  ARCHITECTURE:
//  1. InterpretationEngine produces AnalysisOutput from workout data
//  2. AnalysisOutput contains structured, machine-readable insights
//  3. NarrativeService (future) can use OpenAI to rewrite into natural language
//  4. UI can display either raw structured data or AI-enhanced narrative
//

import Foundation

// MARK: - Analysis Output

/// Structured analysis output produced by the InterpretationEngine.
/// This is the source of truth for workout insights - all data is calculated locally.
struct AnalysisOutput: Codable, Equatable {

    // MARK: - Core Analysis

    /// Overall sentiment of the workout analysis
    let sentiment: AnalysisSentiment

    /// Confidence score (0.0 - 1.0) based on data quality
    let confidence: Double

    /// Timestamp when analysis was generated
    let generatedAt: Date

    // MARK: - Workout Metrics

    /// Key metrics extracted from the workout
    let metrics: WorkoutMetrics

    // MARK: - Insights

    /// Individual insight points with structured data
    let insights: [StructuredInsight]

    // MARK: - Recommendations

    /// Actionable recommendations based on the analysis
    let recommendations: [StructuredRecommendation]

    // MARK: - Pattern Analysis

    /// Patterns detected from workout history
    let patterns: [DetectedPattern]

    // MARK: - Recovery Context

    /// Recovery-related context if available
    let recoveryContext: RecoveryContext?

    // MARK: - Nutrition Context

    /// Nutrition/hydration context if available
    let nutritionContext: NutritionContext?

    // MARK: - Data Completeness

    /// Information about data quality/completeness
    let dataCompleteness: DataCompleteness?

    // MARK: - Generated Text (Local Rules)

    /// Summary text generated by local rules
    let localSummary: String

    /// Detailed interpretation from local rules
    let localInterpretation: String

    /// Recommendation text from local rules
    let localRecommendation: String?

    // MARK: - AI-Enhanced Text (Future)

    /// AI-rewritten summary (nil until OpenAI integration)
    var aiEnhancedSummary: String?

    /// AI-rewritten interpretation (nil until OpenAI integration)
    var aiEnhancedInterpretation: String?

    /// Whether AI enhancement is available
    var hasAIEnhancement: Bool {
        aiEnhancedSummary != nil || aiEnhancedInterpretation != nil
    }

    // MARK: - Display Helpers

    /// Returns the best available summary (AI-enhanced if available, otherwise local)
    var displaySummary: String {
        aiEnhancedSummary ?? localSummary
    }

    /// Returns the best available interpretation
    var displayInterpretation: String {
        aiEnhancedInterpretation ?? localInterpretation
    }
}

// MARK: - Analysis Sentiment

enum AnalysisSentiment: String, Codable, CaseIterable {
    case positive = "positive"
    case neutral = "neutral"
    case caution = "caution"

    var displayName: String {
        switch self {
        case .positive: return "Great workout"
        case .neutral: return "Solid effort"
        case .caution: return "Take note"
        }
    }
}

// MARK: - Workout Metrics

struct WorkoutMetrics: Codable, Equatable {
    let duration: TimeInterval
    let calories: Int
    let averageHeartRate: Int?
    let maxHeartRate: Int?
    let distance: Double?
    let intensity: String
    let workoutType: String

    /// Computed efficiency score (0-100)
    var efficiencyScore: Int? {
        guard let avgHR = averageHeartRate, avgHR > 0 else { return nil }
        // Simple efficiency: lower HR for similar output = better
        let baseScore = 70
        let hrAdjustment = avgHR < 140 ? 15 : (avgHR > 170 ? -15 : 0)
        return min(100, max(0, baseScore + hrAdjustment))
    }
}

// MARK: - Structured Insight

struct StructuredInsight: Codable, Equatable, Identifiable {
    let id: UUID
    let category: InsightCategory
    let sentiment: AnalysisSentiment
    let weight: Double // 0.0 - 1.0, higher = more important
    let icon: String
    let title: String
    let detail: String
    let dataPoints: [String: String]? // Raw data backing this insight

    init(
        id: UUID = UUID(),
        category: InsightCategory,
        sentiment: AnalysisSentiment,
        weight: Double,
        icon: String,
        title: String,
        detail: String,
        dataPoints: [String: String]? = nil
    ) {
        self.id = id
        self.category = category
        self.sentiment = sentiment
        self.weight = weight
        self.icon = icon
        self.title = title
        self.detail = detail
        self.dataPoints = dataPoints
    }
}

enum InsightCategory: String, Codable, CaseIterable {
    case heartRate = "heart_rate"
    case duration = "duration"
    case intensity = "intensity"
    case recovery = "recovery"
    case pattern = "pattern"
    case sleep = "sleep"
    case hydration = "hydration"
    case progress = "progress"
}

// MARK: - Structured Recommendation

struct StructuredRecommendation: Codable, Equatable, Identifiable {
    let id: UUID
    let priority: RecommendationPriority
    let category: RecommendationCategory
    let title: String
    let detail: String
    let actionable: Bool

    init(
        id: UUID = UUID(),
        priority: RecommendationPriority,
        category: RecommendationCategory,
        title: String,
        detail: String,
        actionable: Bool = true
    ) {
        self.id = id
        self.priority = priority
        self.category = category
        self.title = title
        self.detail = detail
        self.actionable = actionable
    }
}

enum RecommendationPriority: String, Codable, CaseIterable {
    case high = "high"
    case medium = "medium"
    case low = "low"
}

enum RecommendationCategory: String, Codable, CaseIterable {
    case nextWorkout = "next_workout"
    case recovery = "recovery"
    case nutrition = "nutrition"
    case sleep = "sleep"
    case technique = "technique"
    case general = "general"
}

// MARK: - Detected Pattern

struct DetectedPattern: Codable, Equatable, Identifiable {
    let id: UUID
    let patternType: PatternType
    let description: String
    let trend: PatternTrend
    let significance: Double // 0.0 - 1.0
    let dataRange: String? // e.g., "last 7 days"

    init(
        id: UUID = UUID(),
        patternType: PatternType,
        description: String,
        trend: PatternTrend,
        significance: Double,
        dataRange: String? = nil
    ) {
        self.id = id
        self.patternType = patternType
        self.description = description
        self.trend = trend
        self.significance = significance
        self.dataRange = dataRange
    }
}

enum PatternType: String, Codable, CaseIterable {
    case fitnessImproving = "fitness_improving"
    case overtraining = "overtraining"
    case recovery = "recovery"
    case consistency = "consistency"
    case varietyNeeded = "variety_needed"
}

enum PatternTrend: String, Codable, CaseIterable {
    case improving = "improving"
    case stable = "stable"
    case declining = "declining"
}

// MARK: - Recovery Context

struct RecoveryContext: Codable, Equatable {
    let sleepHours: Double?
    let sleepQuality: String?
    let hrvScore: Double?
    let restingHeartRate: Int?
    let readinessScore: Int?
    let stressLevel: String?

    var hasData: Bool {
        sleepHours != nil || hrvScore != nil || readinessScore != nil
    }
}

// MARK: - Nutrition Context

struct NutritionContext: Codable, Equatable {
    let waterIntakeMl: Int?
    let calories: Int?
    let proteinGrams: Int?
    let carbsGrams: Int?
    let fatGrams: Int?
    let date: Date

    /// Whether any nutrition data is available
    var hasData: Bool {
        waterIntakeMl != nil || calories != nil || proteinGrams != nil
    }

    /// Whether water intake data is available
    var hasWaterData: Bool {
        waterIntakeMl != nil
    }

    /// Whether macro data is available
    var hasMacroData: Bool {
        calories != nil || proteinGrams != nil || carbsGrams != nil
    }

    /// Water intake in liters for display
    var waterIntakeLiters: Double? {
        guard let ml = waterIntakeMl else { return nil }
        return Double(ml) / 1000.0
    }

    /// Hydration status based on intake
    var hydrationStatus: HydrationStatus {
        guard let ml = waterIntakeMl else { return .unknown }
        switch ml {
        case 0..<1000: return .low
        case 1000..<2000: return .moderate
        case 2000..<3000: return .good
        default: return .excellent
        }
    }
}

enum HydrationStatus: String, Codable {
    case unknown = "unknown"
    case low = "low"
    case moderate = "moderate"
    case good = "good"
    case excellent = "excellent"

    var displayText: String {
        switch self {
        case .unknown: return "Not tracked"
        case .low: return "Low - drink more water"
        case .moderate: return "Moderate"
        case .good: return "Good hydration"
        case .excellent: return "Excellent hydration"
        }
    }
}

// MARK: - Data Completeness

struct DataCompleteness: Codable, Equatable {
    let hasHeartRateData: Bool
    let hasSleepData: Bool
    let hasNutritionData: Bool
    let hasWaterData: Bool
    let hasRecoveryData: Bool

    /// Overall completeness score (0.0 - 1.0)
    var score: Double {
        let factors: [Bool] = [
            hasHeartRateData,
            hasSleepData,
            hasNutritionData,
            hasWaterData,
            hasRecoveryData
        ]
        let trueCount = factors.filter { $0 }.count
        return Double(trueCount) / Double(factors.count)
    }

    /// Human-readable completeness level
    var level: CompletenessLevel {
        switch score {
        case 0..<0.2: return .minimal
        case 0.2..<0.5: return .partial
        case 0.5..<0.8: return .good
        default: return .complete
        }
    }

    /// Notes about missing data
    var missingDataNotes: [String] {
        var notes: [String] = []
        if !hasHeartRateData { notes.append("Heart rate data would improve accuracy") }
        if !hasSleepData { notes.append("Sleep data helps understand recovery") }
        if !hasNutritionData { notes.append("Nutrition data enables deeper insights") }
        if !hasWaterData { notes.append("Water tracking helps assess hydration") }
        return notes
    }
}

enum CompletenessLevel: String, Codable {
    case minimal = "minimal"
    case partial = "partial"
    case good = "good"
    case complete = "complete"

    var displayText: String {
        switch self {
        case .minimal: return "Limited data"
        case .partial: return "Partial data"
        case .good: return "Good data coverage"
        case .complete: return "Complete data"
        }
    }
}

// MARK: - Analysis Output Builder

extension AnalysisOutput {

    /// Create a basic analysis output for a workout
    static func create(
        from workout: Workout,
        context: DailyContext?,
        nutritionContext: NutritionContext? = nil,
        insights: [StructuredInsight],
        recommendations: [StructuredRecommendation],
        patterns: [DetectedPattern],
        localSummary: String,
        localInterpretation: String,
        localRecommendation: String?
    ) -> AnalysisOutput {

        // Determine overall sentiment from insights
        let sentimentCounts = insights.reduce(into: [AnalysisSentiment: Double]()) { counts, insight in
            counts[insight.sentiment, default: 0] += insight.weight
        }
        let dominantSentiment = sentimentCounts.max { $0.value < $1.value }?.key ?? .neutral

        // Calculate confidence based on data quality
        let confidence = calculateConfidence(workout: workout, context: context, nutrition: nutritionContext)

        // Build metrics
        let metrics = WorkoutMetrics(
            duration: workout.duration,
            calories: workout.calories,
            averageHeartRate: workout.averageHeartRate,
            maxHeartRate: workout.maxHeartRate,
            distance: workout.distance,
            intensity: workout.intensity.rawValue,
            workoutType: workout.type.rawValue
        )

        // Build recovery context
        let recoveryContext: RecoveryContext? = context.map { ctx in
            RecoveryContext(
                sleepHours: ctx.sleepHours,
                sleepQuality: ctx.sleepQuality.rawValue,
                hrvScore: ctx.hrvScore,
                restingHeartRate: ctx.restingHeartRate,
                readinessScore: ctx.readinessScore,
                stressLevel: ctx.stressLevel.rawValue
            )
        }

        // Build data completeness
        let dataCompleteness = DataCompleteness(
            hasHeartRateData: workout.averageHeartRate != nil,
            hasSleepData: context?.sleepHours != nil,
            hasNutritionData: nutritionContext?.hasMacroData ?? false,
            hasWaterData: nutritionContext?.hasWaterData ?? false,
            hasRecoveryData: context?.readinessScore != nil || context?.hrvScore != nil
        )

        return AnalysisOutput(
            sentiment: dominantSentiment,
            confidence: confidence,
            generatedAt: Date(),
            metrics: metrics,
            insights: insights,
            recommendations: recommendations,
            patterns: patterns,
            recoveryContext: recoveryContext,
            nutritionContext: nutritionContext,
            dataCompleteness: dataCompleteness,
            localSummary: localSummary,
            localInterpretation: localInterpretation,
            localRecommendation: localRecommendation
        )
    }

    private static func calculateConfidence(workout: Workout, context: DailyContext?, nutrition: NutritionContext? = nil) -> Double {
        var confidence = 0.4 // Base confidence

        // Heart rate data increases confidence
        if workout.averageHeartRate != nil { confidence += 0.15 }
        if workout.maxHeartRate != nil { confidence += 0.1 }

        // Context data increases confidence
        if context != nil { confidence += 0.1 }

        // Nutrition/water data increases confidence
        if let nutrition = nutrition {
            if nutrition.hasWaterData { confidence += 0.05 }
            if nutrition.hasMacroData { confidence += 0.1 }
        }

        // Manual entry has lower confidence
        if workout.isManualEntry { confidence -= 0.1 }

        return min(1.0, max(0.0, confidence))
    }
}

// MARK: - Conversion from WorkoutInterpretation

extension AnalysisOutput {

    /// Convert legacy WorkoutInterpretation to AnalysisOutput
    init(from interpretation: WorkoutInterpretation, workout: Workout, context: DailyContext?) {
        // Map sentiment
        let sentiment: AnalysisSentiment
        switch interpretation.sentiment {
        case .positive: sentiment = .positive
        case .neutral: sentiment = .neutral
        case .caution: sentiment = .caution
        }

        // Build insights from bullet points
        let insights: [StructuredInsight] = interpretation.bulletPoints.enumerated().map { index, bullet in
            let bulletSentiment: AnalysisSentiment
            switch bullet.sentiment {
            case .positive: bulletSentiment = .positive
            case .neutral: bulletSentiment = .neutral
            case .caution: bulletSentiment = .caution
            }

            return StructuredInsight(
                category: .intensity,
                sentiment: bulletSentiment,
                weight: 0.8 - (Double(index) * 0.1),
                icon: bullet.icon,
                title: bullet.text,
                detail: bullet.text
            )
        }

        // Build recommendation
        let recommendations: [StructuredRecommendation]
        if !interpretation.recommendationText.isEmpty {
            recommendations = [
                StructuredRecommendation(
                    priority: .medium,
                    category: .nextWorkout,
                    title: "Next Steps",
                    detail: interpretation.recommendationText
                )
            ]
        } else {
            recommendations = []
        }

        // Build metrics
        let metrics = WorkoutMetrics(
            duration: workout.duration,
            calories: workout.calories,
            averageHeartRate: workout.averageHeartRate,
            maxHeartRate: workout.maxHeartRate,
            distance: workout.distance,
            intensity: workout.intensity.rawValue,
            workoutType: workout.type.rawValue
        )

        // Build recovery context
        let recoveryContext: RecoveryContext? = context.map { ctx in
            RecoveryContext(
                sleepHours: ctx.sleepHours,
                sleepQuality: ctx.sleepQuality.rawValue,
                hrvScore: ctx.hrvScore,
                restingHeartRate: ctx.restingHeartRate,
                readinessScore: ctx.readinessScore,
                stressLevel: ctx.stressLevel.rawValue
            )
        }

        // Build data completeness
        let dataCompleteness = DataCompleteness(
            hasHeartRateData: workout.averageHeartRate != nil,
            hasSleepData: context?.sleepHours != nil,
            hasNutritionData: false,
            hasWaterData: false,
            hasRecoveryData: context?.readinessScore != nil || context?.hrvScore != nil
        )

        self.init(
            sentiment: sentiment,
            confidence: workout.isManualEntry ? 0.6 : 0.8,
            generatedAt: Date(),
            metrics: metrics,
            insights: insights,
            recommendations: recommendations,
            patterns: [],
            recoveryContext: recoveryContext,
            nutritionContext: nil,
            dataCompleteness: dataCompleteness,
            localSummary: interpretation.summaryText,
            localInterpretation: interpretation.interpretationText,
            localRecommendation: interpretation.recommendationText
        )
    }
}
